server:
  port: 8092

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/airport
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use-jdbc-metadata-defaults: false

---
kafka:
  topic:
    check-in: com.bdsystems.airport.check-in

---
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
