server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/airport
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use-jdbc-metadata-defaults: false
